from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import os
from datetime import datetime

class ReportGenerator:
    @staticmethod
    def generate_summary_report(student, registrations, total_hours, output_filename=None):
        """
        Generate a PDF summary report for a student.
        Returns the filepath of the generated PDF.
        """
        if output_filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_filename = f"summary_report_{student.user.username}_{timestamp}.pdf"
        
        # Ensure directory exists
        output_dir = os.path.join('static', 'reports')
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        filepath = os.path.join(output_dir, output_filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            alignment=1, # Center
            spaceAfter=30
        )
        story.append(Paragraph("Volunteer Service Summary Report", title_style))
        story.append(Spacer(1, 20))

        # Student Info
        info_style = ParagraphStyle(
            'InfoStyle',
            parent=styles['Normal'],
            fontSize=12,
            leading=16
        )
        
        story.append(Paragraph(f"<b>Student Name:</b> {student.first_name} {student.surname}", info_style))
        story.append(Paragraph(f"<b>School/University:</b> {student.school or 'N/A'}", info_style))
        story.append(Paragraph(f"<b>Username:</b> {student.user.username}", info_style))
        story.append(Paragraph(f"<b>Email:</b> {student.user.email}", info_style))
        story.append(Paragraph(f"<b>Date Generated:</b> {datetime.now().strftime('%B %d, %Y')}", info_style))
        story.append(Spacer(1, 20))
        
        # Summary Stats
        story.append(Paragraph(f"<b>Total Verified Hours:</b> {total_hours}", info_style))
        story.append(Paragraph(f"<b>Total Events Attended:</b> {len(registrations)}", info_style))
        story.append(Spacer(1, 20))

        # Table Data
        data = [['Event Title', 'Organization', 'Date', 'Hours', 'Status']]
        
        for reg in registrations:
            date_str = reg.event.date_time.strftime('%Y-%m-%d')
            status = "Verified" if reg.is_verified else "Pending/Unverified"
            hours = str(reg.hours_earned) if reg.hours_earned else "0"
            
            data.append([
                reg.event.title[:30] + ('...' if len(reg.event.title) > 30 else ''), # Truncate long titles
                reg.event.organization.organization_name[:25],
                date_str,
                hours,
                status
            ])

        # Table Style
        table = Table(data, colWidths=[2.5*inch, 2.0*inch, 1.0*inch, 0.8*inch, 1.2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(table)
        
        # Footer
        story.append(Spacer(1, 40))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.grey,
            alignment=1
        )
        story.append(Paragraph("Generated by ACP Volunteer System", footer_style))

        doc.build(story)
        return filepath

    @staticmethod
    def generate_admin_dashboard_report(stats, recent_activities, output_filename=None):
        """
        Generate a PDF summary report for the Admin Dashboard.
        stats: dict containing total_students, total_hours, pending_orgs, active_orgs
        recent_activities: list of ActivityLog objects
        """
        if output_filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_filename = f"admin_dashboard_report_{timestamp}.pdf"
        
        # Ensure directory exists
        output_dir = os.path.join('static', 'reports')
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
        filepath = os.path.join(output_dir, output_filename)
        
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            alignment=1, # Center
            spaceAfter=30
        )
        story.append(Paragraph("Admin Dashboard Summary Report", title_style))
        story.append(Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", styles['Normal']))
        story.append(Spacer(1, 20))
        
        # System Statistics
        story.append(Paragraph("<b>System Statistics</b>", styles['Heading2']))
        story.append(Spacer(1, 10))
        
        stats_data = [
            ['Metric', 'Value'],
            ['Active Students', str(stats.get('total_students', 0))],
            ['Total Service Hours', f"{stats.get('total_hours', 0):.1f}"],
            ['Pending Approvals', str(stats.get('pending_orgs', 0))],
            ['Active Organizations', str(stats.get('active_orgs', 0))]
        ]
        
        stats_table = Table(stats_data, colWidths=[3*inch, 2*inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 30))

        # Recent Activities
        story.append(Paragraph("<b>Recent Activities</b>", styles['Heading2']))
        story.append(Spacer(1, 10))

        activity_data = [['Time', 'User', 'Activity', 'IP Address']]
        
        if recent_activities:
            for activity in recent_activities:
                activity_data.append([
                    activity.timestamp.strftime('%Y-%m-%d %H:%M'),
                    activity.user.username,
                    activity.description[:40] + ('...' if len(activity.description) > 40 else ''),
                    activity.ip_address or 'N/A'
                ])
        else:
            activity_data.append(['-', '-', 'No recent activities', '-'])

        activity_table = Table(activity_data, colWidths=[1.5*inch, 1.2*inch, 2.5*inch, 1.2*inch])
        activity_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        
        story.append(activity_table)
        
        # Footer
        story.append(Spacer(1, 40))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.grey,
            alignment=1
        )
        story.append(Paragraph("Generated by ACP Volunteer System", footer_style))

        doc.build(story)
        return filepath
